
let manLs = '<h1>ls</h1>';
        manLs +="<h2>Name</h2>";
        manLs +="<p>ls - list directory contents </p>";
        manLs +="<h2>Synopsis</h2>";
        manLs +="<b>ls</b> [<i>OPTION</i>]... [<i>FILE</i>]...";
        manLs +="<h2>Description</h2>";
        manLs +="<p>List information about the FILEs (the current directory by default). Sort entries alphabetically if none of <b>-cftuvSUX</b> nor <b>--sort</b>.";
        manLs +="<p>Mandatory arguments to long options are mandatory for short options too.";
        manLs +="<dl compact>";
        manLs +="<dt><b>-a</b>, <b>--all</b>";
        manLs +="<dd>do not ignore entries starting with .";
        manLs +="<dt><b>-A</b>, <b>--almost-all</b>";
        manLs +="<dd>do not list implied . and ..";
        manLs +="<dt><b>--author</b>";
        manLs +="<dd>with <b>-l</b>, print the author of each file";
        manLs +="<dt><b>-b</b>, <b>--escape</b>";
        manLs +="<dd>print octal escapes for nongraphic characters";
        manLs +="<dt><b>--block-size</b>=<i>SIZE</i>";
        manLs +="<dd>use SIZE-byte blocks. See SIZE format below";
        manLs +="<dt><b>-B</b>, <b>--ignore-backups</b>";
        manLs +="<dd>do not list implied entries ending with ~";
        manLs +="<dt><b>-c</b>";
        manLs +="<dd>with <b>-lt</b>: sort by, and show, ctime (time of last modification of file status information) with <b>-l</b>: show ctime and sort by name otherwise:";
        manLs +="sort by ctime";
        manLs +="<dt><b>-C</b>";
        manLs +="<dd>list entries by columns";
        manLs +="<dt><b>--color</b>[=<i>WHEN</i>]";
        manLs +="<dd>colorize the output. WHEN defaults to 'always' or can be 'never' or 'auto'. More info below";
        manLs +="<dt><b>-d</b>, <b>--directory</b>";
        manLs +="<dd>list directory entries instead of contents, and do not dereference symbolic links";
        manLs +="<dt><b>-D</b>, <b>--dired</b>";
        manLs +="<dd>generate output designed for Emacs' dired mode";
        manLs +="<dt><b>-f</b>";
        manLs +="<dd>do not sort, enable <b>-aU</b>, disable <b>-ls --color</b>";
        manLs +="<dt><b>-F</b>, <b>--classify</b>";
        manLs +="<dd>append indicator (one of */=&gt;@|) to entries";
        manLs +="<dt><b>--file-type</b>";
        manLs +="<dd>likewise, except do not append '*'";
        manLs +="<dt><b>--format</b>=<i>WORD</i>";
        manLs +="<dd>across <b>-x</b>, commas <b>-m</b>, horizontal <b>-x</b>, long <b>-l</b>, single-column <b>-1</b>, verbose <b>-l</b>, vertical <b>-C</b>";
        manLs +="<dt><b>--full-time</b>";
        manLs +="<dd>like <b>-l --time-style</b>=<i>full-iso</i>";
        manLs +="<dt><b>-g</b>";
        manLs +="<dd>like <b>-l</b>, but do not list owner";
        manLs +="<dt><b>--group-directories-first</b>";
        manLs +="<dd>group directories before files.";
        manLs +="<dt>augment with a <b>--sort</b> option, but any";
        manLs +="<dd>use of <b>--sort</b>=<i>none</i> (<b>-U</b>) disables grouping";
        manLs +="<dt><b>-G</b>, <b>--no-group</b>";
        manLs +="<dd>in a long listing, don't print group names";
        manLs +="<dt><b>-h</b>, <b>--human-readable</b>";
        manLs +="<dd>with <b>-l</b>, print sizes in human readable format (e.g., 1K 234M 2G)";
        manLs +="<dt><b>--si</b>";
        manLs +="<dd>likewise, but use powers of 1000 not 1024";
        manLs +="<dt><b>-H</b>, <b>--dereference-command-line</b>";
        manLs +="<dd>follow symbolic links listed on the command line";
        manLs +="<dt><b>--dereference-command-line-symlink-to-dir</b>";
        manLs +="<dd>follow each command line symbolic link that points to a directory";
        manLs +="<dt><b>--hide</b>=<i>PATTERN</i>";
        manLs +="<dd>do not list implied entries matching shell PATTERN (overridden by <b>-a</b> or <b>-A</b>)";
        manLs +="<dt><b>--indicator-style</b>=<i>WORD</i>";
        manLs +="<dd>append indicator with style WORD to entry names: none (default), slash (<b>-p</b>), file-type (<b>--file-type</b>), classify (<b>-F</b>)";
        manLs +="<dt><b>-i</b>, <b>--inode</b>";
        manLs +="<dd>print the index number of each file";
        manLs +="<dt><b>-I</b>, <b>--ignore</b>=<i>PATTERN</i>";
        manLs +="<dd>do not list implied entries matching shell PATTERN";
        manLs +="<dt><b>-k</b>";
        manLs +="<dd>like <b>--block-size</b>=<i>1K</i>";
        manLs +="<dt><b>-l</b>";
        manLs +="<dd>use a long listing format";
        manLs +="<dt><b>-L</b>, <b>--dereference</b>";
        manLs +="<dd>when showing file information for a symbolic link, show information for the file the link references rather than for the link itself";
        manLs +="<dt><b>-m</b>";
        manLs +="<dd>fill width with a comma separated list of entries";
        manLs +="<dt><b>-n</b>, <b>--numeric-uid-gid</b>";
        manLs +="<dd>like <b>-l</b>, but list numeric user and group IDs";
        manLs +="<dt><b>-N</b>, <b>--literal</b>";
        manLs +="<dd>print raw entry names (don't treat e.g. control characters specially)";
        manLs +="<dt><b>-o</b>";
        manLs +="<dd>like <b>-l</b>, but do not list group information";
        manLs +="<dt><b>-p</b>, <b>--indicator-style</b>=<i>slash</i>";
        manLs +="<dd>append / indicator to directories";
        manLs +="<dt><b>-q</b>, <b>--hide-control-chars</b>";
        manLs +="<dd>print ? instead of non graphic characters";
        manLs +="<dt><b>--show-control-chars</b>";
        manLs +="<dd>show non graphic characters as-is (default unless program is 'ls' and output is a terminal)";
        manLs +="<dt><b>-Q</b>, <b>--quote-name</b>";
        manLs +="<dd>enclose entry names in double quotes";
        manLs +="<dt><b>--quoting-style</b>=<i>WORD</i>";
        manLs +="<dd>use quoting style WORD for entry names: literal, locale, shell, shell-always, c, escape";
        manLs +="<dt><b>-r</b>, <b>--reverse</b>";
        manLs +="<dd>reverse order while sorting";
        manLs +="<dt><b>-R</b>, <b>--recursive</b>";
        manLs +="<dd>list subdirectories recursively";
        manLs +="<dt><b>-s</b>, <b>--size</b>";
        manLs +="<dd>print the allocated size of each file, in blocks";
        manLs +="<dt><b>-S</b>";
        manLs +="<dd>sort by file size";
        manLs +="<dt><b>--sort</b>=<i>WORD</i>";
        manLs +="<dd>sort by WORD instead of name: none <b>-U</b>, extension <b>-X</b>, size <b>-S</b>, time <b>-t</b>, version <b>-v</b>";
        manLs +="<dt><b>--time</b>=<i>WORD</i>";
        manLs +="<dd>with <b>-l</b>, show time as WORD instead of modification time: atime <b>-u</b>, access <b>-u</b>, use <b>-u</b>, ctime <b>-c</b>, or status <b>-c</b>; use";
        manLs +="specified time as sort key if <b>--sort</b>=<i>time</i>";
        manLs +="<dt><b>--time-style</b>=<i>STYLE</i>";
        manLs +="<dd>with <b>-l</b>, show times using style STYLE: full-iso, long-iso, iso, locale, +FORMAT. FORMAT is interpreted like 'date'; if FORMAT is";
        manLs +="FORMAT1&lt;newline&gt;FORMAT2, FORMAT1 applies to non-recent files and FORMAT2 to recent files; if STYLE is prefixed with 'posix-', STYLE takes effect only";
        manLs +="outside the POSIX locale";
        manLs +="<dt><b>-t</b>";
        manLs +="<dd>sort by modification time";
        manLs +="<dt><b>-T</b>, <b>--tabsize</b>=<i>COLS</i>";
        manLs +="<dd>assume tab stops at each COLS instead of 8";
        manLs +="<dt><b>-u</b>";
        manLs +="<dd>with <b>-lt</b>: sort by, and show, access time with <b>-l</b>: show access time and sort by name otherwise: sort by access time";
        manLs +="<dt><b>-U</b>";
        manLs +="<dd>do not sort; list entries in directory order";
        manLs +="<dt><b>-v</b>";
        manLs +="<dd>natural sort of (version) numbers within text";
        manLs +="<dt><b>-w</b>, <b>--width</b>=<i>COLS</i>";
        manLs +="<dd>assume screen width instead of current value";
        manLs +="<dt><b>-x</b>";
        manLs +="<dd>list entries by lines instead of by columns";
        manLs +="<dt><b>-X</b>";
        manLs +="<dd>sort alphabetically by entry extension";
        manLs +="<dt><b>-1</b>";
        manLs +="<dd>list one file per line</dl>";
        manLs +="<p>SELinux options:";
        manLs +="<dl compact>";
        manLs +="<dt><b>--lcontext</b>";
        manLs +="<dd>Display security context. Enable <b>-l</b>. Lines will probably be too wide for most displays.";
        manLs +="<dt><b>-Z</b>, <b>--context</b>";
        manLs +="<dd>Display security context so it fits on most displays. Displays only mode, user, group, security context and file name.";
        manLs +="<dt><b>--scontext</b>";
        manLs +="<dd>Display only security context and file name.";
        manLs +="<dt><b>--help</b>";
        manLs +="<dd>display this help and exit";
        manLs +="<dt><b>--version</b>";
        manLs +="<dd>output version information and exit</dl>";
        manLs +="<p>SIZE may be (or may be an integer optionally followed by) one of following: KB 1000, K 1024, MB 1000*1000, M 1024*1024, and so on for G, T, P, E, Z, Y.";
        manLs +="<p>Using color to distinguish file types is disabled both by default and with <b>--color</b>=<i>never</i>. With <b>--color</b>=<i>auto</i>, ls emits color";
        manLs +="codes only when standard output is connected to a terminal. The LS_COLORS environment variable can change the settings. Use the dircolors command to set it.";
        manLs +="<h3>Exit status:</h3>";
        manLs +="<ol>";
        manLs +="<li>if OK,";
        manLs +="<li>if minor problems (e.g., cannot access subdirectory),";
        manLs +="<li>if serious trouble (e.g., cannot access command-line argument).</ol>";
        manLs +="<h2>Author</h2>";
        manLs +="Written by Richard M. Stallman and David MacKenzie.";
        
module.exports = { manCat }




