let manRm = "<h2>Name</h2>";
        manRm += "rm - remove files or directories";
        manRm += "<h2>Synopsis</h2>";
        manRm += "<b>rm</b> [<i>OPTION</i>]... <i>FILE</i>...";
        manRm += "<h2>Description</h2>";
        manRm += "<p>This manual page documents the GNU version of <b>rm</b>. <b>rm</b> removes each specified file.";
        manRm += "By default, it does not remove directories.</p>";
        manRm += "<p>If the <i>-I</i> or <i>--interactive=once</i> option is given, and there are more than three files or the <i>-r</i>, <i>-R</i>, or <i>--recursive</i> are";
        manRm += "given, then <b>rm</b> prompts the user for whether to proceed with the entire operation. If the response is not affirmative, the entire command is aborted.";
        manRm += "<p>Otherwise, if a file is unwritable, standard input is a terminal, and the <i>-f</i> or <i>--force</i> option is not given, or the <i>-i</i> or";
        manRm += "<i>--interactive=always</i> option is given, <b>rm</b> prompts the user for whether to remove the file. If the response is not affirmative, the file is";
        manRm += "skipped.</p>";
        manRm += "<h2>Options</h2>";
        manRm += "<p>Remove (unlink) the <b>FILE</b>(s).";
        manRm += "<dl compact>";
        manRm += "<dt><b>-f</b>, <b>--force</b>";
        manRm += "<dd>ignore nonexistent files, never prompt";
        manRm += "<dt><b>-i</b>";
        manRm += "<dd>prompt before every removal";
        manRm += "<dt><b>-I</b>";
        manRm += "<dd>prompt once before removing more than three files, or when removing recursively. Less intrusive than <b>-i</b>, while still giving protection against most";
        manRm += "mistakes";
        manRm += "<dt><b>--interactive</b>[=<i>WHEN</i>]";
        manRm += "<dd>prompt according to WHEN: never, once (<b>-I</b>), or always (<b>-i</b>). Without WHEN, prompt always";
        manRm += "<dt><b>--one-file-system</b>";
        manRm += "<dd>when removing a hierarchy recursively, skip any directory that is on a file system different from that of the corresponding command line argument";
        manRm += "<dt><b>--no-preserve-root</b>";
        manRm += "<dd>do not treat '/' specially";
        manRm += "<dt><b>--preserve-root</b>";
        manRm += "<dd>do not remove '/' (default)";
        manRm += "<dt><b>-r</b>, <b>-R</b>, <b>--recursive</b>";
        manRm += "<dd>remove directories and their contents recursively";
        manRm += "<dt><b>-v</b>, <b>--verbose</b>";
        manRm += "<dd>explain what is being done";
        manRm += "<dt><b>--help</b>";
        manRm += "<dd>display this help and exit";
        manRm += "<dt><b>--version</b>";
        manRm += "<dd>output version information and exit</dl>";
        manRm += "<p>By default, rm does not remove directories. Use the <b>--recursive</b> (<b>-r</b> or <b>-R</b>) option to remove each listed directory, too, along with all";
        manRm += "of its contents.";
        manRm += "<p>To remove a file whose name starts with a '-', for example '-foo', use one of these commands:";
        manRm += "<dl compact>";
        manRm += "<dt>rm <b>-- -foo</b>";
        manRm += "<dt>rm ./-foo</dl>";
        manRm += "<p>Note that if you use rm to remove a file, it is usually possible to recover the contents of that file. If you want more assurance that the contents are";
        manRm += "truly unrecoverable, consider using shred.</p>";
        manRm += "<h2>Author</h2>";
        manRm += "<p>Written by Paul Rubin, David MacKenzie, Richard M. Stallman, and Jim Meyering.</p>";

exports.manRm = manRm;


let importMan = require('./manFileReferenceCaller');
